### PR TITLE
fixing some option availability glitches

### PR DESCRIPTION
**Pull request by docrostov**
fixing two issues identified by TES in extinguisher & cargo short tiles. 

going to leave this open overnight so that i can watch for other glitches in tomorrow's run and fix them all in one PR.

### CODE REVIEW

**Comment by docrostov** [comment]
also, when merged, closes #41

**Comment by Malibu-Stacey** [comment]
As this is a bit of a "catch-all" PR, can I suggest a bump to version number. It's in Settings.ash
All the new stuff you merged from @uthuluc is more than enough to justify it & the last time it was done was by Beldur in December.

**Comment by docrostov** [comment]
add more aggressive bowling ball reminders if users set 

```tourGuideBowlingBallSupernag = true```

**Comment by docrostov** [comment]
new thing to add -- https://github.com/uthuluc/TourGuide/blob/master/iotm2022unbrella tes umbrella tile

will resolve #42 (effectively; still some quest changes but frankly those are minor enough i do not care lol)

**Pull request merged**
